export const MKSZ628Course1402Example1Data1 = [
  {index: 1, name: '去菜场买菜', amount: 98, type: '食'},
  {index: 2, name: '王者荣耀充值', amount: 648, type: '玩'},
  {index: 3, name: '给楼下小黑买烤肠', amount: 12, type: '食'},
  {index: 4, name: '买过年衣服', amount: 465, type: '衣'},
  {index: 5, name: '慕课网买课程', amount: 599, type: '学'},
  {index: 6, name: '停车费', amount: 500, type: '行'},
  {index: 7, name: '家庭宽带费用', amount: 1200, type: '住'},
  {index: 8, name: '汽车加油', amount: 280, type: '行'},
  {index: 9, name: '和同学聚餐', amount: 300, type: '食'},
  {index: 10, name: '下个月房租', amount: 1000, type: '住'},
  {index: 11, name: '买过年衣服', amount: 465, type: '衣'},
  {index: 12, name: '慕课网买课程', amount: 599, type: '学'},
  {index: 13, name: '停车费', amount: 500, type: '行'},
  {index: 14, name: '家庭宽带费用', amount: 1200, type: '住'},
  {index: 15, name: '汽车加油', amount: 280, type: '行'},
]

export const MKSZ628Course1402Example1Data2 = [
  {index: 1, name: '去菜场买菜', amount: 198, type: '食'},
  {index: 2, name: '王者荣耀充值', amount: 248, type: '玩'},
  {index: 3, name: '给楼下小黑买烤肠', amount: 68, type: '食'},
  {index: 4, name: '买过年衣服', amount: 65, type: '衣'},
  {index: 5, name: '慕课网买课程', amount: 399, type: '学'},
  {index: 6, name: '停车费', amount: 350, type: '行'},
  {index: 7, name: '家庭宽带费用', amount: 1200, type: '住'},
  {index: 8, name: '汽车加油', amount: 480, type: '行'},
  {index: 9, name: '和同学聚餐', amount: 110, type: '食'},
  {index: 10, name: '下个月房租', amount: 600, type: '住'},
  {index: 11, name: '慕课网买课程', amount: 399, type: '学'},
  {index: 12, name: '停车费', amount: 350, type: '行'},
  {index: 13, name: '家庭宽带费用', amount: 1800, type: '住'},
  {index: 14, name: '汽车加油', amount: 480, type: '行'},
  {index: 15, name: '和同学聚餐', amount:96, type: '食'},
];
